# Generated by Django 6.1.1 on 2026-09-08 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('board', models.CharField(blank=True, max_length=100)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('goal', models.TextField(blank=True)),
                ('preferred_daily_study_minutes', models.PositiveIntegerField(default=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
