# Generated by Django 6.1.1 on 2026-09-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='enrolled_profiles', to='academics.subject'),
        ),
    ]
