# Generated by Django 6.1.1 on 2026-09-09 11:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('learn', 'Learn'), ('practice', 'Practice'), ('revise', 'Revise'), ('test', 'Test'), ('homework', 'Homework'), ('reading', 'Reading'), ('doubt', 'Doubt')], default='learn', max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_tasks', to='academics.chapter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_tasks', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_tasks', to='academics.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_tasks', to='academics.topic')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
